networks:
  network-nnp:
    driver: bridge

services:
  postgresql:
    container_name: postgresql
    image: postgres:14.6
    container_name: postgres-nodechat
    networks:
      - network-nnp
    ports:
      - '5432:5432'
    volumes:
      - './var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=nodechat
      - POSTGRES_USER=postgres
