networks:
  network-nnp:
    driver: bridge

services:
  postgresql:
    image: postgres:14.6
    container_name: postgres-nodechat
    networks:
      - network-nnp
    ports:
      - '5432:5432'
    volumes:
      - './var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=nodechat
      - POSTGRES_USER=postgres
  nginx:
    image: nginx
    container_name: nginx-nodechat
    networks:
      - network-nnp
    ports:
      - '80:80'
    volumes:
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_PORT=80
  app:
    build: .
    image: xcirel/dockernode
    command: npm start   
    networks:
      - network-nnp
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/share/nodeapp-chat


